# Generated by Django 4.2.15 on 2024-08-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'USER', 'verbose_name_plural': 'USERS'},
        ),
        migrations.AddField(
            model_name='usermodel',
            name='organization',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
