# Generated by Django 4.2.15 on 2024-08-30 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_options_usermodel_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_event', models.CharField(max_length=255)),
                ('event_picture', models.FileField(blank=True, null=True, upload_to='')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('event_organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
