# Generated by Django 4.2.15 on 2024-09-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='event',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
