# Generated by Django 4.2.15 on 2024-09-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_event_amount_event_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=20),
        ),
    ]
