# Generated by Django 4.2.15 on 2024-09-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_event_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
