# Generated by Django 4.2.15 on 2024-09-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_event_event_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_picture',
            field=models.FileField(blank=True, null=True, upload_to='event_picture/'),
        ),
    ]
