# Generated by Django 4.2.15 on 2024-09-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_event_event_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='total_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
