# Generated by Django 4.2.15 on 2024-09-07 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_event_event_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.event')),
            ],
            options={
                'verbose_name': 'Contestant',
                'verbose_name_plural': 'Contestants',
            },
        ),
        migrations.CreateModel(
            name='ContestanInfoImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestantdata_images', models.FileField(blank=True, null=True, upload_to='')),
                ('contestant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.contestantinfo')),
            ],
            options={
                'verbose_name': 'Contestant Image',
                'verbose_name_plural': 'Contestant Images',
            },
        ),
    ]
