# Generated by Django 4.2.15 on 2024-09-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestaninfoimages',
            name='contestantdata_images',
            field=models.FileField(blank=True, null=True, upload_to='contestants/'),
        ),
    ]
