# Generated by Django 4.2.15 on 2024-09-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_contestaninfoimages_contestantdata_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestaninfoimages',
            name='prime_image',
            field=models.BooleanField(default=False),
        ),
    ]
